server:
    allowTools:
        - weather-api
        - github-api
        - post-example
    name: curl-examples-server
tools:
    - description: Weather API request with query parameters
      name: weather-api
      requestTemplate:
        method: GET
        url: https://api.openweathermap.org/data/2.5/weather?q=London&appid=YOUR_API_KEY
      responseTemplate:
        body: ""
    - description: GitHub API to fetch user information
      name: github-api
      requestTemplate:
        method: GET
        url: https://api.github.com/users/octocat
      responseTemplate:
        body: ""
    - description: Example POST request with JSON data
      name: post-example
      requestTemplate:
        method: POST
        url: https://example.com/api/users
      responseTemplate:
        body: ""
